# Generated by Django 5.2.11 on 2026-02-25 01:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_route_geojson', models.JSONField(blank=True, null=True)),
                ('actual_route_geojson', models.JSONField(blank=True, null=True)),
                ('planned_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('planned_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='orders.freightorder')),
            ],
            options={
                'verbose_name': 'Order Route',
            },
        ),
        migrations.CreateModel(
            name='GPSPing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bearing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_pings', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_pings', to='orders.freightorder')),
            ],
            options={
                'verbose_name': 'GPS Ping',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', '-timestamp'], name='tracking_gp_driver__276e42_idx'), models.Index(fields=['order', '-timestamp'], name='tracking_gp_order_i_1aa739_idx')],
            },
        ),
    ]
