# Generated by Django 5.2.11 on 2026-02-25 01:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('cargo_type', models.CharField(choices=[('GENERAL', 'General / Mixed'), ('FRAGILE', 'Fragile Goods'), ('HAZARDOUS', 'Hazardous Materials'), ('LIVESTOCK', 'Livestock'), ('REFRIGERATED', 'Refrigerated / Perishable'), ('BULK', 'Bulk / Agricultural'), ('CONSTRUCTION', 'Construction Materials'), ('ELECTRONICS', 'Electronics')], default='GENERAL', max_length=20)),
                ('cargo_description', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('special_instructions', models.TextField(blank=True)),
                ('cargo_photos', models.JSONField(blank=True, default=list)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(default='Dakar', max_length=100)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_contact_name', models.CharField(blank=True, max_length=100)),
                ('pickup_contact_phone', models.CharField(blank=True, max_length=20)),
                ('pickup_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_contact_name', models.CharField(blank=True, max_length=100)),
                ('delivery_contact_phone', models.CharField(blank=True, max_length=20)),
                ('delivery_deadline', models.DateTimeField(blank=True, null=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted — Awaiting Carriers'), ('BIDDING', 'Receiving Bids'), ('ASSIGNED', 'Carrier Assigned'), ('PICKUP_PENDING', 'Driver En Route to Pickup'), ('PICKED_UP', 'Cargo Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered — Awaiting Confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], db_index=True, default='DRAFT', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_broker', to=settings.AUTH_USER_MODEL)),
                ('required_vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicletype')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_shipper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freight Order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Bid price in XOF', max_digits=12)),
                ('message', models.TextField(blank=True)),
                ('estimated_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=15)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_placed', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='orders.freightorder')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Order Bid',
                'ordering': ['price', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('driver_en_route_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('in_transit_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='proof_of_delivery/')),
                ('proof_note', models.TextField(blank=True)),
                ('proof_signature', models.TextField(blank=True, help_text='Base64 signature or name')),
                ('delivery_confirmed_by_shipper', models.BooleanField(default=False)),
                ('shipper_rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5', null=True)),
                ('driver_rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5', null=True)),
                ('shipper_review', models.TextField(blank=True)),
                ('driver_review', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_driver', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='orders.freightorder')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicle')),
                ('accepted_bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderbid')),
            ],
            options={
                'verbose_name': 'Order Assignment',
            },
        ),
        migrations.AddIndex(
            model_name='freightorder',
            index=models.Index(fields=['status', 'created_at'], name='orders_frei_status_38cfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='freightorder',
            index=models.Index(fields=['shipper', 'status'], name='orders_frei_shipper_843d1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderbid',
            unique_together={('order', 'carrier')},
        ),
    ]
