# Generated by Django 5.0.9 on 2026-03-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_make_assignment_vehicle_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freightorder",
            name="delivery_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="freightorder",
            name="delivery_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="freightorder",
            name="pickup_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="freightorder",
            name="pickup_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
