# Generated by Django 5.2.12 on 2026-03-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_increase_latlng_decimal_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderassignment",
            name="pickup_proof_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderassignment",
            name="pickup_proof_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="proof_of_pickup/"
            ),
        ),
    ]
