# Generated by Django 5.2.11 on 2026-02-25 01:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_fr', models.CharField(blank=True, help_text='French name', max_length=100)),
                ('name_wo', models.CharField(blank=True, help_text='Wolof name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_payload_kg', models.PositiveIntegerField(help_text='Maximum payload in kg')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for frontend', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('make', models.CharField(blank=True, help_text='e.g. Mercedes-Benz', max_length=100)),
                ('model', models.CharField(blank=True, help_text='e.g. Actros', max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG')], default='DIESEL', max_length=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('payload_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('owner', models.ForeignKey(limit_choices_to={'role__in': ['DRIVER', 'FLEET_MANAGER']}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('REGISTRATION', 'Carte Grise'), ('INSURANCE', 'Assurance'), ('INSPECTION', 'Visite Technique'), ('PERMIT', 'Permis de Transport'), ('OTHER', 'Autre')], max_length=20)),
                ('file', models.FileField(upload_to='vehicles/documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'ordering': ['document_type'],
            },
        ),
    ]
