# Generated by Django 5.2.12 on 2026-06-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="axle_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="gross_weight_kg",
            field=models.PositiveIntegerField(
                blank=True, help_text="Gross vehicle weight in kg", null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="registration_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="trailer_type",
            field=models.CharField(
                blank=True, help_text="e.g. Flatbed, Reefer, Dry Van", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                blank=True, help_text="Vehicle Identification Number", max_length=17
            ),
        ),
    ]
