# Generated by Django 5.2.12 on 2026-06-08 23:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="bank_routing_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="cdl_endorsements",
            field=models.CharField(
                blank=True, help_text="e.g. hazmat, tanker, doubles", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="dispatch_contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="dispatch_contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="driving_experience_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="drug_testing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLIANT", "Compliant"),
                    ("NOT_COMPLIANT", "Non-Compliant"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="equipment_types",
            field=models.CharField(
                blank=True, help_text="Types of equipment handled", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="home_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_class",
            field=models.CharField(
                blank=True, help_text="A, B, C, etc.", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="license_state",
            field=models.CharField(
                blank=True, help_text="Issuing country/region", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="medical_card_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="medical_card_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="drivers/medical/"
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACH", "ACH / Bank Transfer"),
                    ("CHECK", "Check"),
                    ("WAVE", "Wave"),
                    ("ORANGE_MONEY", "Orange Money"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="preferred_lanes",
            field=models.TextField(
                blank=True, help_text="Preferred routes or service area"
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SHIPPER", "Shipper"),
                    ("DRIVER", "Driver"),
                    ("CARRIER", "Carrier"),
                    ("ADMIN", "Admin"),
                ],
                default="SHIPPER",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CarrierProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_company_name", models.CharField(blank=True, max_length=255)),
                (
                    "dot_number",
                    models.CharField(blank=True, help_text="DOT number", max_length=50),
                ),
                (
                    "mc_number",
                    models.CharField(
                        blank=True, help_text="MC / authority number", max_length=50
                    ),
                ),
                (
                    "operating_authority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INTERSTATE", "Interstate"),
                            ("INTRASTATE", "Intrastate"),
                            ("BOTH", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, help_text="Tax ID / NINEA", max_length=100
                    ),
                ),
                (
                    "w9_document",
                    models.FileField(blank=True, null=True, upload_to="carriers/w9/"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/carriers/"
                    ),
                ),
                ("company_address", models.TextField(blank=True)),
                (
                    "company_city",
                    models.CharField(blank=True, default="Dakar", max_length=100),
                ),
                (
                    "company_country",
                    models.CharField(blank=True, default="Senegal", max_length=100),
                ),
                ("primary_contact_name", models.CharField(blank=True, max_length=255)),
                ("primary_contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("dispatch_contact_name", models.CharField(blank=True, max_length=255)),
                ("dispatch_contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "auto_liability_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cargo_insurance_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("insurance_provider", models.CharField(blank=True, max_length=255)),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                (
                    "certificate_of_insurance",
                    models.FileField(
                        blank=True, null=True, upload_to="carriers/insurance/"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACH", "ACH / Bank Transfer"),
                            ("CHECK", "Check"),
                            ("WAVE", "Wave"),
                            ("ORANGE_MONEY", "Orange Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bank_account_name", models.CharField(blank=True, max_length=255)),
                ("bank_account_number", models.CharField(blank=True, max_length=100)),
                ("bank_routing_number", models.CharField(blank=True, max_length=100)),
                ("preferred_lanes", models.TextField(blank=True)),
                ("service_area", models.TextField(blank=True)),
                ("availability_notes", models.TextField(blank=True)),
                (
                    "drug_testing_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("NOT_COMPLIANT", "Non-Compliant"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("carrier_agreement_accepted", models.BooleanField(default=False)),
                (
                    "carrier_agreement_accepted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_loads", models.PositiveIntegerField(default=0)),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrier Profile",
            },
        ),
    ]
