# Generated by Django 5.2.12 on 2026-06-09 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_driverprofile_bank_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drivers",
                to="accounts.carrierprofile",
            ),
        ),
    ]
