# Generated by Django 5.2.12 on 2026-06-13 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
