# Generated by Django 5.2.12 on 2026-06-18 15:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_shipper_legal_fields_driver_insurance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SHIPPER", "Shipper"),
                    ("DRIVER", "Driver"),
                    ("CARRIER", "Carrier"),
                    ("BROKER", "Broker"),
                    ("ADMIN", "Admin"),
                ],
                default="SHIPPER",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BrokerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=3.5, max_digits=5),
                ),
                ("service_area", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/brokers/"
                    ),
                ),
                ("total_matches", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                (
                    "total_commission_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broker Profile",
            },
        ),
    ]
