# Generated by Django 6.0.6 on 2026-06-24 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_adminpermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminpermission",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
