# Generated by Django 6.0.6 on 2026-06-28 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_workspaceswitchlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceswitchlog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
