# Generated by Django 6.0.6 on 2026-06-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_workspaceswitchlog_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrierprofile",
            name="is_available",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
