# Generated by Django 5.2.11 on 2026-02-25 01:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provider', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('FREE_MONEY', 'Free Money (Expresso)'), ('CASH', 'Cash on Delivery')], max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text='External transaction ID from the payment provider', max_length=255, null=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=15)),
                ('failure_reason', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.freightorder')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_pa_order_i_ed562a_idx'), models.Index(fields=['payer', 'status'], name='payments_pa_payer_i_2437ab_idx')],
            },
        ),
    ]
