# Generated by Django 6.0.6 on 2026-07-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paytechconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("WAVE", "Wave"),
                    ("ORANGE_MONEY", "Orange Money"),
                    ("FREE_MONEY", "Free Money (Expresso)"),
                    ("PAYTECH", "PayTech (Carte bancaire / Mobile Money)"),
                    ("CASH", "Cash on Delivery"),
                ],
                max_length=20,
            ),
        ),
    ]
